server:
  port: 8003

#Eureka的配置 把test注册到Eureka里面
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

spring:
  application:
    name: filesys_server
  #文件上传限制
  servlet:
    multipart:
      max-file-size: 10240MB #单个文件大小
      max-request-size: 102400MB #总文件大小