server:
  port: 8001

#mybatis配置
#mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  #mapper-locations: classpath:mybatis/mapper/*.xml
  #type-aliases-package: com.ding.uaa.model

#spring配置
#spring:
  #datasource:
  #type: com.alibaba.druid.pool.DruidDataSource
  #driver-class-name: com.mysql.jdbc.Driver
  #url: jdbc:mysql://localhost:3306/ding?useUnicode=true&characterEncoding=utf-8
  #username: root
  #password: DC635241.1

    #main:
      #允许覆盖OAuth2放在容器中的Bean对象
    # allow-bean-definition-overriding: true

#Eureka的配置 把uaa注册到Eureka里面
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: user_satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # jwt密钥
  jwt-secret-key: go8cnxdbfs12120uaasatokennokey

spring:
  application:
    name: uaa_satoken_server
  #文件上传限制
  servlet:
    multipart:
      max-file-size: 10240MB #单个文件大小
      max-request-size: 102400MB #总文件大小