server:
  port: 8001

#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.ding.uaa.model

#spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ding?useUnicode=true&characterEncoding=utf-8
    username: root
    password: DC635241.1

#Eureka的配置 把uaa注册到Eureka里面
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
